version: "3.9"
services:
  nc:
    image: nextcloud:apache
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    ports:
      - 80:80
    depends_on:
      - db
    restart: always
    volumes:
      - nc_data:/var/www/html
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.nc==true
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.database==true
volumes:
  db_data:
  nc_data:
